export default {
  peace: require("../assets/peace.jpg"),
  timeMachine: require("../assets/time-machine.jpg"),
  logo: require("../assets/formidable-logo.svg"),
  graph1: require("../assets/1.png"),
  lamp: require("../assets/lamp.jpg"),
  ohNo: require("../assets/oh-no.gif"),
  stackoverflow1: require("../assets/stackoverflow1.png"),
  oldJs: require("../assets/old-js.png"),
  oldSchool: require("../assets/old-school.jpg"),
  newStyles: require("../assets/new-styles.jpg"),
  client: require("../assets/client.jpg"),
  client2: require("../assets/client2.jpg"),
  stacksChange: require("../assets/stacks-change.jpg"),
  newPlayers: require("../assets/new-players.png"),
  mix: require("../assets/mix2.jpg"),
  security: require("../assets/security.png"),
  diff: require("../assets/diff.gif"),
  demo1: require("../assets/demo1.gif"),
  concerns: require("../assets/concerns.png"),
  compose0: require("../assets/compose0.png"),
  compose1: require("../assets/compose1.png"),
  compose2: require("../assets/compose2.png"),
  pray2: require("../assets/pray2.gif"),
  conversion: require("../assets/conversion.png"),
}
